FROM microsoft/aspnetcore:2.0-nanoserver-1709 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0-nanoserver-1709 AS build
WORKDIR /src
COPY DroneFormToTCOMS/DroneFormToTCOMS.csproj DroneFormToTCOMS/
RUN dotnet restore DroneFormToTCOMS/DroneFormToTCOMS.csproj
COPY . .
WORKDIR /src/DroneFormToTCOMS
RUN dotnet build DroneFormToTCOMS.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish DroneFormToTCOMS.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "DroneFormToTCOMS.dll"]
